name: test
env:
  MY_APP_NAME: "MyApp"
  MY_PACKAGE_NAME: "MyApp-vesion-${{github.sha}}"
  
on: 
  push:
    branches:
      - master
      
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      VAR_DATE: "${{env.date}}"
      VAR_TIME: "${{env.time}}"
    steps:
      - name: step1
        run: |
          echo "My App Name :${{env.MY_APP_NAME}} ======= My Pckg Name :${{env.MY_PACKAGE_NAME}}"
          echo "Date is ${{env.VAR_DATE}} and time is ${{VAR_TIME}}"
        
