name: test
env:
  MY_APP_NAME: "MyApp"
  MY_PACKAGE_NAME: "MyApp-vesion-${{github.sha}}"
  
on: 
  push:
    branches:
      - master
      
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      VAR_TEXT: "NO TEXT"
    steps:
      - uses: action/checkout@v2
      - name: step1
        run: |
          echo "My App Name :${{env.MY_APP_NAME}} ======= My Pckg Name :${{env.MY_PACKAGE_NAME}}"
          echo "Text variable is ${{ env.VAR_TEXT }}"
          echo "Local var = ${{ env.LOCAL_VAR }}"
          ls -la
          pwd
        env:
          LOCAL_VAR: "LOCAL VAR"
        
