name: test
env:
  MY_APP_NAME: "MyApp"
  MY_PACKAGE_NAME: "MyApp-vesion-${{github.sha}}"
  
on: 
  push:
    branches:
      -master
      
jobs:
  job-1:
    runs-on: Windows
    steps:
      - name: step1
        run: echo "My App Name :${{env.MY_PACKAGE_NAME}}"
        
